### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by dragon0170** [paust-team/shapleq#182]
An error occurred while building shapleq on macOS.

### Build environment
1. MacBook Pro 14
    - macOS 12.3.1
    - Apple M1 Pro
    - go1.17.7 darwin/amd64
    - Apple clang version 13.1.6 (clang-1316.0.21.2.3)
2. iMac 27-inch 2020
    - macOS 12.3.1
    - 3.8 GHz 8-core Intel Core i7
    - go1.17.8 darwin/amd64
    - Apple clang version 13.1.6 (clang-1316.0.21.2.3)

### Issue
I followed the "build & install from source" process at the README.
On both computers, `make build` command failed for same error.
```bash
if [ -d .git ]; then \
		git submodule update --init --recursive; \
	fi
Submodule '_thirdparty/protobuf' (https://github.com/protocolbuffers/protobuf.git) registered for path '_thirdparty/protobuf'
Submodule '_thirdparty/rocksdb' (https://github.com/facebook/rocksdb.git) registered for path '_thirdparty/rocksdb'
Cloning into '/Users/kevin/paust/shapleq/_thirdparty/protobuf'...
Cloning into '/Users/kevin/paust/shapleq/_thirdparty/rocksdb'...
Submodule path '_thirdparty/protobuf': checked out 'd662ec9c2e4f8ca21cb500b25cfe7430511014b2'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path '_thirdparty/protobuf/third_party/benchmark'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path '_thirdparty/protobuf/third_party/googletest'
Cloning into '/Users/kevin/paust/shapleq/_thirdparty/protobuf/third_party/benchmark'...
Cloning into '/Users/kevin/paust/shapleq/_thirdparty/protobuf/third_party/googletest'...
Submodule path '_thirdparty/protobuf/third_party/benchmark': checked out '5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8'
Submodule path '_thirdparty/protobuf/third_party/googletest': checked out '5ec7f0c4a113e2f18ac2c6cc7df51ad6afc24081'
Submodule path '_thirdparty/rocksdb': checked out 'fcf3d75f3f022a6a55ff1222d6b06f8518d38c7c'
LD_LIBRARY_PATH=:/usr/local/lib
make build-protobuf
protoc is already built. Run make rebuild-protobuf to remove existing one and rebuild it.
make compile-protobuf
rm -f /Users/kevin/paust/shapleq/proto/*.go
protoc --proto_path=/Users/kevin/paust/shapleq/proto --go_out=/Users/kevin/paust/shapleq/proto /Users/kevin/paust/shapleq/proto/*.proto
make build-rocksdb
make rebuild-rocksdb
rm -rf /Users/kevin/paust/shapleq/_thirdparty/rocksdb/build
mkdir -p /Users/kevin/paust/shapleq/_thirdparty/rocksdb/build
cd /Users/kevin/paust/shapleq/_thirdparty/rocksdb/build && cmake .. -DCMAKE_TARGET_MESSAGES=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPORTABLE=ON -DWITH_TESTS=OFF \
	-DWITH_BENCHMARK_TOOLS=OFF -DWITH_SNAPPY=ON -DUSE_RTTI=ON -DWITH_GFLAGS=OFF \
	&& make -j 4 install
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: /usr/bin/git (found version "2.32.0 (Apple Git-132)")
-- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER
-- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER - Success
-- Performing Test HAS_ARMV8_CRC
-- Performing Test HAS_ARMV8_CRC - Success
--  HAS_ARMV8_CRC yes
-- Performing Test HAVE_SSE42
-- Performing Test HAVE_SSE42 - Failed
-- Performing Test BUILTIN_ATOMIC
-- Performing Test BUILTIN_ATOMIC - Success
-- Performing Test HAS_LIBURING
-- Performing Test HAS_LIBURING - Failed
-- Performing Test HAVE_THREAD_LOCAL
-- Performing Test HAVE_THREAD_LOCAL - Success
-- Enabling RTTI
-- Performing Test HAVE_FALLOCATE
-- Performing Test HAVE_FALLOCATE - Failed
-- Performing Test HAVE_SYNC_FILE_RANGE_WRITE
-- Performing Test HAVE_SYNC_FILE_RANGE_WRITE - Failed
-- Performing Test HAVE_PTHREAD_MUTEX_ADAPTIVE_NP
-- Performing Test HAVE_PTHREAD_MUTEX_ADAPTIVE_NP - Failed
-- Looking for malloc_usable_size
-- Looking for malloc_usable_size - not found
-- Looking for sched_getcpu
-- Looking for sched_getcpu - not found
-- Looking for getauxval
-- Looking for getauxval - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- JNI library is disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/kevin/paust/shapleq/_thirdparty/rocksdb/build
[  0%] Building CXX object CMakeFiles/rocksdb.dir/cache/cache_entry_roles.cc.o
[  1%] Building CXX object CMakeFiles/rocksdb.dir/cache/cache.cc.o
[  1%] Building CXX object CMakeFiles/rocksdb.dir/cache/cache_reservation_manager.cc.o
[  2%] Building CXX object CMakeFiles/rocksdb-shared.dir/cache/cache.cc.o
[  2%] Building CXX object CMakeFiles/rocksdb-shared.dir/cache/cache_entry_roles.cc.o
[  2%] Building CXX object CMakeFiles/rocksdb.dir/cache/clock_cache.cc.o
[  2%] Building CXX object CMakeFiles/rocksdb.dir/cache/lru_cache.cc.o
[  2%] Building CXX object CMakeFiles/rocksdb.dir/cache/sharded_cache.cc.o
[  2%] Building CXX object CMakeFiles/rocksdb-shared.dir/cache/cache_reservation_manager.cc.o
[  2%] Building CXX object CMakeFiles/rocksdb-shared.dir/cache/clock_cache.cc.o
[  3%] Building CXX object CMakeFiles/rocksdb.dir/db/arena_wrapped_db_iter.cc.o
[  3%] Building CXX object CMakeFiles/rocksdb-shared.dir/cache/lru_cache.cc.o
[  3%] Building CXX object CMakeFiles/rocksdb-shared.dir/cache/sharded_cache.cc.o
[  3%] Building CXX object CMakeFiles/rocksdb.dir/db/blob/blob_fetcher.cc.o
[  3%] Building CXX object CMakeFiles/rocksdb.dir/db/blob/blob_file_addition.cc.o
[  3%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/arena_wrapped_db_iter.cc.o
[  4%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/blob/blob_fetcher.cc.o
[  4%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/blob/blob_file_addition.cc.o
[  4%] Building CXX object CMakeFiles/rocksdb.dir/db/blob/blob_file_builder.cc.o
[  4%] Building CXX object CMakeFiles/rocksdb.dir/db/blob/blob_file_cache.cc.o
[  4%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/blob/blob_file_builder.cc.o
[  4%] Building CXX object CMakeFiles/rocksdb.dir/db/blob/blob_file_garbage.cc.o
[  4%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/blob/blob_file_cache.cc.o
[  4%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/blob/blob_file_garbage.cc.o
[  4%] Building CXX object CMakeFiles/rocksdb.dir/db/blob/blob_file_meta.cc.o
[  4%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/blob/blob_file_meta.cc.o
[  5%] Building CXX object CMakeFiles/rocksdb.dir/db/blob/blob_file_reader.cc.o
[  6%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/blob/blob_file_reader.cc.o
[  6%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/blob/blob_garbage_meter.cc.o
[  6%] Building CXX object CMakeFiles/rocksdb.dir/db/blob/blob_garbage_meter.cc.o
[  6%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/blob/blob_log_format.cc.o
[  6%] Building CXX object CMakeFiles/rocksdb.dir/db/blob/blob_log_format.cc.o
[  6%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/blob/blob_log_sequential_reader.cc.o
[  6%] Building CXX object CMakeFiles/rocksdb.dir/db/blob/blob_log_sequential_reader.cc.o
[  6%] Building CXX object CMakeFiles/rocksdb.dir/db/blob/blob_log_writer.cc.o
[  6%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/blob/blob_log_writer.cc.o
[  6%] Building CXX object CMakeFiles/rocksdb.dir/db/blob/prefetch_buffer_collection.cc.o
[  6%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/blob/prefetch_buffer_collection.cc.o
[  6%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/builder.cc.o
[  7%] Building CXX object CMakeFiles/rocksdb.dir/db/builder.cc.o
[  7%] Building CXX object CMakeFiles/rocksdb.dir/db/c.cc.o
[  7%] Building CXX object CMakeFiles/rocksdb.dir/db/column_family.cc.o
[  7%] Building CXX object CMakeFiles/rocksdb.dir/db/compaction/compaction.cc.o
[  8%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/c.cc.o
[  8%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/column_family.cc.o
[  8%] Building CXX object CMakeFiles/rocksdb.dir/db/compaction/compaction_iterator.cc.o
[  8%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/compaction/compaction.cc.o
[  8%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/compaction/compaction_iterator.cc.o
[  8%] Building CXX object CMakeFiles/rocksdb.dir/db/compaction/compaction_picker.cc.o
[  8%] Building CXX object CMakeFiles/rocksdb.dir/db/compaction/compaction_job.cc.o
[  9%] Building CXX object CMakeFiles/rocksdb.dir/db/compaction/compaction_picker_fifo.cc.o
[  9%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/compaction/compaction_picker.cc.o
[  9%] Building CXX object CMakeFiles/rocksdb.dir/db/compaction/compaction_picker_level.cc.o
[  9%] Building CXX object CMakeFiles/rocksdb.dir/db/compaction/compaction_picker_universal.cc.o
[  9%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/compaction/compaction_job.cc.o
[ 10%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/compaction/compaction_picker_fifo.cc.o
[ 10%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/compaction/compaction_picker_level.cc.o
[ 10%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/compaction/compaction_picker_universal.cc.o
[ 10%] Building CXX object CMakeFiles/rocksdb.dir/db/compaction/sst_partitioner.cc.o
[ 10%] Building CXX object CMakeFiles/rocksdb.dir/db/convenience.cc.o
[ 10%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/compaction/sst_partitioner.cc.o
[ 10%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/convenience.cc.o
[ 10%] Building CXX object CMakeFiles/rocksdb.dir/db/db_filesnapshot.cc.o
[ 11%] Building CXX object CMakeFiles/rocksdb.dir/db/db_impl/compacted_db_impl.cc.o
[ 11%] Building CXX object CMakeFiles/rocksdb.dir/db/db_impl/db_impl.cc.o
[ 11%] Building CXX object CMakeFiles/rocksdb.dir/db/db_impl/db_impl_write.cc.o
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/db_impl/db_impl.cc:9:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/db_impl/db_impl.h:22:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/column_family.h:17:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/memtable_list.h:16:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/memtable.h:22:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/range_tombstone_fragmenter.h:15:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/pinned_iterators_manager.h:12:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/table/internal_iterator.h:16:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/table/format.h:22:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/options/cf_options.h:12:
/Users/kevin/paust/shapleq/_thirdparty/rocksdb/options/db_options.h:119:12: error: definition of implicit copy assignment operator for 'MutableDBOptions' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
  explicit MutableDBOptions(const MutableDBOptions& options) = default;
           ^
/Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/db_impl/db_impl.cc:1229:27: note: in implicit copy assignment operator for 'rocksdb::MutableDBOptions' first required here
      mutable_db_options_ = new_options;
                          ^
[ 11%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/db_filesnapshot.cc.o
[ 11%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/db_impl/compacted_db_impl.cc.o
1 error generated.
make[5]: *** [CMakeFiles/rocksdb.dir/db/db_impl/db_impl.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
[ 12%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/db_impl/db_impl.cc.o
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/db_impl/db_impl.cc:9:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/db_impl/db_impl.h:22:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/column_family.h:17:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/memtable_list.h:16:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/memtable.h:22:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/range_tombstone_fragmenter.h:15:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/pinned_iterators_manager.h:12:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/table/internal_iterator.h:16:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/table/format.h:22:
In file included from /Users/kevin/paust/shapleq/_thirdparty/rocksdb/options/cf_options.h:12:
/Users/kevin/paust/shapleq/_thirdparty/rocksdb/options/db_options.h:119:12: error: definition of implicit copy assignment operator for 'MutableDBOptions' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
  explicit MutableDBOptions(const MutableDBOptions& options) = default;
           ^
/Users/kevin/paust/shapleq/_thirdparty/rocksdb/db/db_impl/db_impl.cc:1229:27: note: in implicit copy assignment operator for 'rocksdb::MutableDBOptions' first required here
      mutable_db_options_ = new_options;
                          ^
[ 12%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/db_impl/db_impl_write.cc.o
make[4]: *** [CMakeFiles/rocksdb.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 12%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/db_impl/db_impl_compaction_flush.cc.o
[ 12%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/db_impl/db_impl_files.cc.o
1 error generated.
make[5]: *** [CMakeFiles/rocksdb-shared.dir/db/db_impl/db_impl.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [CMakeFiles/rocksdb-shared.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [rebuild-rocksdb] Error 2
make[1]: *** [build-rocksdb] Error 2
make: *** [build] Error 2
```

**Comment by elon0823** [comment]
### Cause
That error occurs on a macOS version 12.3.1 which is the latest macOS version. I've succeeded in building the ShapleQ on macOS version 12.2.x, but I just failed to build on macOS 12.3.1.  As the clang version increases(to 13.1.6), it seems that the existing deprecated operation is excluded.

### Workaround
* Update the rocksdb with recent version which is compatible with the late version of the grocksdb

**Comment by elon0823** [comment]
resolved from #188 and #190
